services:

  http-server-projeto-korp:

    build:
      context: ./app

    image: http-server-projeto-korp:1.0

    container_name: http-server-projeto-korp

    restart: unless-stopped

    expose:
      - "8080"

    networks:
      - korp-network

  nginx:

    image: nginx:latest

    container_name: nginx

    restart: unless-stopped

    depends_on:
      - http-server-projeto-korp

    ports:
      - "80:80"

    volumes:
      - ./nginx/http-server-projeto-korp.conf:/etc/nginx/conf.d/default.conf:ro

    networks:
      - korp-network

networks:

  korp-network:

    driver: bridge