---
- name: Criar diretório do projeto
  file:
    path: "{{ projeto_dir }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"
  become: true

- name: Clonar repositório
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ projeto_dir }}"
    version: "{{ repo_branch }}"
    force: true
    update: true
    accept_hostkey: true
  become: true
  become_user: ubuntu

- name: Executar Docker Compose
  ansible.builtin.command:
    cmd: "{{ docker_compose_cmd }} up -d --build"
    chdir: "{{ projeto_dir }}"
  become: true

- name: Aguardar containers iniciarem
  pause:
    seconds: 20