---

- name: Validar endpoint da aplicação
  uri:

    url: "{{ projeto_endpoint }}"

    method: GET

    return_content: yes

    status_code: 200

  register: resposta

- name: Exibir resposta da aplicação
  debug:
    var: resposta.json

- name: Listar containers
  command: docker ps

  register: docker_ps

- name: Mostrar containers
  debug:
    var: docker_ps.stdout_lines