---
- name: Validar endpoint da aplicação
  ansible.builtin.uri:
    url: "{{ projeto_endpoint }}"
    method: GET
    return_content: yes
    status_code: 200
    validate_certs: true

  register: resposta

- name: Exibir resposta da aplicação
  ansible.builtin.debug:
    var: resposta.json

- name: Listar containers
  ansible.builtin.command: docker ps
  register: docker_ps

- name: Mostrar containers
  ansible.builtin.debug:
    var: docker_ps.stdout_lines